# Image tag mặc định cho môi trường dev
# File này sẽ được Jenkins CI Bot tự động cập nhật sau mỗi lần build thành công trên branch main
global:
  imageTag: "95ac2d1"
  imageRepository: "tuandaklak"

# Kiểm soát RAM theo QUY_TAC_RAM_K8S.md
rating:
  backend:
    replicaCount: 0

recommendation:
  backend:
    replicaCount: 0

webhook:
  backend:
    replicaCount: 0

sampledata:
  backend:
    replicaCount: 0

location:
  backend:
    replicaCount: 0

# Tắt Ingress của swagger-ui để tránh conflict với production (yas)
swagger-ui:
  ingress:
    enabled: false

storefront-bff:
  backend:
    hostAliases:
      - ip: "10.99.35.97"
        hostnames:
          - "identity.yas.local.com"
    ingress:
      enabled: true
      host: dev-storefront.yas.local.com
      path: /

backoffice-bff:
  backend:
    hostAliases:
      - ip: "10.99.35.97"
        hostnames:
          - "identity.yas.local.com"
    ingress:
      enabled: true
      host: dev-backoffice.yas.local.com
      path: /

storefront-ui:
  backend:
    hostAliases:
      - ip: "10.99.35.97"
        hostnames:
          - "identity.yas.local.com"

backoffice-ui:
  backend:
    hostAliases:
      - ip: "10.99.35.97"
        hostnames:
          - "identity.yas.local.com"

yas-configuration:
  mediaApplicationConfig:
    yas:
      publicUrl: http://dev-api.yas.local.com/media
