apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tax-retry
  namespace: yas
spec:
  hosts:
  - tax
  http:
  - retries:
      attempts: 3
      perTryTimeout: 5s
      retryOn: 5xx,gateway-error,connect-failure,reset
    route:
    - destination:
        host: tax
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: inventory-retry
  namespace: yas
spec:
  hosts:
  - inventory
  http:
  - retries:
      attempts: 3
      perTryTimeout: 5s
      retryOn: 5xx,gateway-error,connect-failure,reset
    route:
    - destination:
        host: inventory
